### PR TITLE
CB-10957 Remove build-*.xcconfig files from build output

### PR DESCRIPTION
**Pull request by omefire**

### CODE REVIEW

**Comment by shazron** [comment]
This PR removes crucial functionality, namely the inheritance of build settings from the .xcconfig files:
screen shot 2016-04-07 at 4 13 33 pm

It should only remove the .xcconfig files from here in Build Phases for the Target:
screen shot 2016-04-07 at 4 14 25 pm

**Comment by omefire** [comment]
Thanks @shazron, will recheck it and make appropriate changes.

**Comment by omefire** [comment]
can't find a good reference for the .pbxproj file, do you have any link ?

**Comment by shazron** [comment]
Not sure what you mean to do, but I would just load the .xcodeproj file in Xcode and delete those references I mentioned in Copy Bundle Resources? (and only stage those changes, it will try to make other changes that are not needed, like removing quotes).

That might be more work than probably just removing these references:
screen shot 2016-04-08 at 10 08 14 am

as you can see they correspond to the screenshot I used in the last comment.

**Comment by omefire** [comment]
Yes, that's what I just realized. I just loaded it in xcode and deleted those from the 'Build Phases' tab -> 'Copy Bundle Resources'. 
Much easier.

**Comment by omefire** [comment]
@shazron could you please take another look ? This time, I did it via Xcode. I noticed minor diffs between before & after and I think it's due to my version of Xcode(diffs are mainly double quotes vs no quotes)

**Comment by shazron** [comment]
The changes are not good - Xcode has a habit of removing those double quotes, which we need. I mentioned in my last comment " (and only stage those changes, it will try to make other changes that are not needed, like removing quotes)."

So probably manually remove the right changes I mentioned only.

**Comment by shazron** [comment]
See staging patches -> https://git-scm.com/book/en/v2/Git-Tools-Interactive-Staging or use a gui tool like SourceTree to only stage those hunks you need

**Comment by shazron** [comment]
Once you do the changes, you should run "npm test" (as you can see your patch has already failed the create tests in Travis)

**Comment by omefire** [comment]
@shazron I'm merging this in. I've addressed your CR notes.

**Pull request closed without merging**
