### PR TITLE
WIP - update dev deps (with additional TODO list)

### PR DESCRIPTION
**Pull request by brodybits**
### Platforms affected

iOS

### What does this PR do?

Update devDependencies in `master` branch:
- remove `nodeunit`
- _update `jasmine`, `rewire`, and `tmp`_

_to be moved into a separate PR:_
- _update `eslint` devDependencies, using eslint-config-standard@next (^12.0.0-alpha.0) to resolve `[ESLINT_LEGACY_OBJECT_REST_SPREAD]` DeprecationWarning (<https://github.com/standard/eslint-config-standard/issues/123#issuecomment-404772247>)_

_(includes fix to simplify AppVeyor CI install, which was already integrated to `master` branch and will drop out of this PR next time I do a rebase)_

_This can be considered a continuation of the devDep cleanup merged from GH-368._

_TO BE MOVED OUT OF THIS PR:_
- _update `eslint` devDependencies - breaks on deprecated Node.js 4 version; suffers from `[ESLINT_LEGACY_OBJECT_REST_SPREAD]` DeprecationWarning (<https://github.com/standard/eslint-config-standard/issues/123#issuecomment-404772247>)_

_devDep TODO_

- [ ] _While we are updating devDependencies I think we should move them below dependencies. More consistent with cordova-ios, I think more consistent with many other npm projects_

_Extra TODO items outside this PR:_
- [ ] _fix AppVeyor CI as done by dropping support for deprecated Node.js 4 as proposed by GH-375_
- [ ] _drop support for deprecated Node.js 4 version (GH-375), completely remove `node_modules`, drop `bundledDependencies`, and mark next major version_
- [ ] update `dependencies`, which should resolve existing `npm audit` issues _as_ was already done in GH-381 for patch release
- [ ] _review GH-376 - Fixed Get Apple OSX Version method_
- [ ] _GH-377 - increase code coverage and migrate to nyc_
- [ ] _apply similar fixes to cordova-osx (mac OS)_
- [ ] _check if similar fixes are needed on the other platforms_
- [ ] _check if any other Cordova packages still need nyc_

### What testing has been done on this change?

- [x] `npm run unit-tests` succeeds on mac "desktop"
- [x] check that `npm test` items succeed on Travis CI _(skipping deprecated Node.js 4 version due to eslint update)_
- [x] check that `eslint` & `npm run unit-tests` items succeed on AppVeyor CI ~~_(now passes on all covered Node.js versions including deprecated Node.js version 4 if fix proposed in GH-383 is included)_~~ _(skipping deprecated Node.js 4 version due to eslint update)_

### Checklist

- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
- ~~Added automated test coverage as appropriate for this change.~~

### CODE REVIEW

**Comment by erisu** [comment]
@brodybits I just noticed that this PR and some of the PRs I submitted a few weeks ago are inline. I am not sure if you had taken a look at them.

**#375 Remove Node 4 Support**

**#377 Increase Code Code coverage**
Includes dependencies upgrades.
- eslint-config-semistandard
- eslint-config-standard
- eslint-plugin-node
- jasmine
- nyc (ADDED)
- require
- istanbul (DROPED)

**Comment by brodybits** [comment]
Thanks @erisu. I did already reference #375 as GH-375, did not realize that #377 already included nyc. 

I think you can see that I already reviewed and merged #376. I would kinda like to include the tests next, also hold off on dropping deprecated Node.js 4 until we take care of a couple items:
- apply fixes to 4.5.x in case we decide to make another patch release there
- get agreement to bump to next major release (5.0.0-dev)

I will very likely push a few changes to this WIP PR to check CI while checking GH-377 (#377)

**Comment by brodybits** [comment]
This PR includes extra items that I will be moving out:
- eslint-* updates
- additional TODO list

**Comment by brodybits** [comment]
I will probably need 1-2 weeks to go through this. I wouldn't mind if someone else gets a chance to apply the changes on `master`, ideally one at a time.

**Comment by erisu** [comment]
Closing in favor https://github.com/apache/cordova-ios/pull/496 which is now merged.

**Pull request closed without merging**
