### PR TITLE
CB-8485 Support for creating signed archive for iOS

### PR DESCRIPTION
**Pull request by nikhilkh**
Allows the user to specify the provisioning profile and the signing identity using the command line and a build.json file.

### CODE REVIEW

**Comment by nikhilkh** [comment]
@shazron @agrieve Wonder if you can take a look?

**Comment by shazron** [comment]
Looks sound to me. I'll give it a spin later today before I pull it in.

**Comment by mattdsteele** [comment]
Hi folks, I'm trying this out - looks really slick!

I had one question: this produces a signed `.app` file. What's the best way to convert it to an `.ipa` we can install on a device? I found [this StackOverflow](http://stackoverflow.com/a/25006630) post, is running `xcrun` the recommended approach?

**Comment by shazron** [comment]
Yes xcrun

**Comment by nikhilkh** [comment]
This change creates an ipa in addition to .app file by invoking xcrun: https://github.com/MSOpenTech/cordova-ios/commit/ebcc29ef9a2ca4ebe49fd319868a514c0a558499#diff-6a830db18b2f183f537e0d0f98275067R114

**Pull request closed without merging**
