### PR TITLE
CB-13597: (ios) update podfile with ios version 9.0

### PR DESCRIPTION
**Pull request by apare**
Since the release Cordova iOS 4.4.0, only iOS 9 and greater supported
https://cordova.apache.org/announcements/2017/04/26/ios-release.html

### Platforms affected
* ios

### What does this PR do?
* Upgrade the podfile ios version

### What testing has been done on this change?
* install a pod dependency with only support ios 9 (Curbside 3.0.0.0)

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by apare** [comment]
travis error `Version '6.11' not found - try `nvm ls-remote` to browse available versions.`

**Comment by janpio** [comment]
I restarted the build on Travis - maybe it works this time.

**Comment by janpio** [comment]
That worked @apare.

**Comment by surajpindoria** [comment]
LGTM!

**Pull request merged**
