### PR TITLE
Updating unit tests + unit test runner and adding platformAPI addPlugin unit tests

### PR DESCRIPTION
**Pull request by filmaj**
# Summary of Changes

- moved `jasmine.json` to `tests/spec`, next to all the unit tests. eliminates the need to have an extra `spec/` dir at the top level.
- updated `package.json` scripts to use the new jasmine config file located at `tests/spec/jasmine.json`. also updated code coverage command to run the right thing.
- moved `bin/lib/check_reqs.js` and `bin/lib/versions.js` to the project template, under `bin/templates/scripts/cordova/lib`, and had the commands that are runnable globally (i.e. not from within a generated project) be able to reference them. as such, had to update `create.js` to change the require paths on the fly for these scripts. this, however, allows us to reference the build js modules directly, opening them up to unit testing. note that [android uses the same technique](https://github.com/apache/cordova-android/blob/master/bin/lib/create.js#L153-L159), and I think it is worth the tradeoff for eliminating try/catch around requires, calling `require` only at runtime, and allowing these modules to be unit tested.
- finally, added unit tests for platform API addPlugin method.

# Results

Worth noting that global code coverage dropped slightly, as reported by instanbul, but I think that is mostly due to now `check_reqs.js` and `versions.js` falling under the coverage 'umbrella' (and those scripts having little-to-no coverage at all). However, `Api.js`' code coverage went from 35% to 50%.

Please review @shazron.

FYI @stevengill @dpogue @kerrishotts @purplecabbage. Feel free to mention anyone else who you think should review or be aware of these changes.

### CODE REVIEW

**Comment by shazron** [comment]
I cloned your fork and checked out the feature branch with all your commits.
Then:
```
$ npm install --dev
$ npm test
...
> cordova-ios@4.5.0-dev unit-tests /Users/shazron/Desktop/cordova-ios
> jasmine --config=tests/spec/jasmine.json

module.js:457
    throw err;
    ^

Error: Cannot find module './lib/check_reqs'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/shazron/Desktop/cordova-ios/bin/templates/scripts/cordova/Api.js:26:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/shazron/.nvm/versions/node/v6.7.0/bin/node" "/Users/shazron/.nvm/versions/node/v6.7.0/bin/npm" "run" "unit-tests"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! cordova-ios@4.5.0-dev unit-tests: `jasmine --config=tests/spec/jasmine.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cordova-ios@4.5.0-dev unit-tests script 'jasmine --config=tests/spec/jasmine.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cordova-ios package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jasmine --config=tests/spec/jasmine.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cordova-ios
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cordova-ios
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shazron/Desktop/cordova-ios/npm-debug.log
npm ERR! Test failed.  See above for more details.
```

if I do a `git status` I see:
```
$ git status
On branch platform-api-unit-tests
Your branch is up-to-date with 'origin/platform-api-unit-tests'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    bin/templates/scripts/cordova/lib/check_reqs.js
	deleted:    bin/templates/scripts/cordova/lib/versions.js
```

**Comment by filmaj** [comment]
Uh oh 😟 interesting, I don't see that in my local setup.

I must have messed the history up, thanks for checking. I'll try with a fresh clone myself and see if I can repro.

**Comment by filmaj** [comment]
Hmm, the diff just shows that those files were moved?

If you `git checkout -- .` from the repo source, and rerun, do you get the same behaviour?

**Comment by shazron** [comment]
Same error.
Did:
```
$ git checkout -- .
$ npm test
```
and it shows the same two deleted files.

**Comment by filmaj** [comment]
I tried a fresh clone of my branch, `npm install --dev`, and `npm run unit-tests`, and can't repro - runs fine on my end. Also worth noting that those two files were not missing from my fresh clone.

Worth noting that after cloning and `npm install`ing, a bunch of files were changed under node_modules, according to `git`.

At what point in the process does your repo miss the files? After cloning? Or after `npm install`ing? OR maybe during the test run somehow?

**Comment by filmaj** [comment]
I'm trying `npm test` now instead of `npm run unit-tests`... maybe the e2e tests are making changes to the git tree?

**Comment by filmaj** [comment]
Do you run a code-syncing background service like `realsync` or something? Could that be doing it?

**Comment by filmaj** [comment]
Ah, no, wait, I can repro if I run the full `npm test` - although those files are not missing in my git tree (git status is empty). 🤔

**Comment by filmaj** [comment]
Props to @shazron for finding out there was an [integration test munging the cordova-ios repo](https://github.com/apache/cordova-ios/blob/8c77a0b991ace06b470dba9496a24e6ef75c2be3/tests/spec/create.spec.js#L115-L128).

Will remove and re-write as a unit test (in this case, for the `run --list` command).

**Comment by filmaj** [comment]
Made some more changes, rebased, confirmed the unit tests now run on my Windows 10 VM.

Sucks to be running tests conditionally but I'm not sure what other option we have.

**Comment by filmaj** [comment]
Yay, green! And looks like the codecov reporting is fixed too ;)

**Pull request closed without merging**
