### PR TITLE
emit xcodebuild & other spawned CLI commands

### PR DESCRIPTION
**Pull request by oliversalzburg**
### Platforms affected
iOS

### What does this PR do?
It logs the CLI for `xcodebuild`. Please note that this PR expects #477 to be merged also.

### What testing has been done on this change?
None

### CODE REVIEW

**Comment by brodybits** [comment]
> Please note that this PR expects #477 to be merged also.

I think you meant PR #478. I would favor just adding the xcodebuild log fix to PR #478.

**Comment by oliversalzburg** [comment]
@brodybits I wanted to keep this change in a separate PR so it will be listed as a discrete change in possible changelogs and to better track the individual chnage.

I would rebase this PR when #478 is merged, to get a cleaner merge.

**Comment by oliversalzburg** [comment]
This should be all good now :)

**Comment by oliversalzburg** [comment]
@brodybits I pushed another update to put `printCommand: true` in all `superspawn` invokations. I missed that comment earlier.

**Comment by brodybits** [comment]
I just updated the title to better reflect the actual changes, will merge in a few minutes or so.

**Comment by brodybits** [comment]
Merged with title updated again for the sake of clarity. Thanks again @oliversalzburg!

**Pull request merged**
