### PR TITLE
refactor!: cleanup create script

### PR DESCRIPTION
**Pull request by erisu**
### Motivation, Context & Description

This PR refactors the `create` script.

- Remove exported `updateSubprojectHelp`
- Remove exported `update_cordova_subproject`
- Renamed internal function `update_cordova_subproject` to `updateCordovaSubproject`
  - Refactored internal function `updateCordovaSubproject` to take in two static arguments:
    - `projectXcodePath` which is the path to project's xcodeproj
    - `cordovaLibXcodePath` which is the path to the CordovaLib's xcodeproj. (Note: it maybe a symbolic link when `--link` flag is added when installing platform)
  - Improved comments
  - Removed excessive supportive internal methods
    - `AbsParentPath`
    - `AbsProjectPath`
    - `relpath`
    - `updateSubprojectHelp`
- Cleanup `copyScript`
  - Begin consolidating items into the new template location for a single line `copySync`
  - Removed string replace line for files `apple-*`. No longer support the platform-centric so the files can be hardcoded for CLI.
- Rename and refactored `copyTemplateFiles` to `copyNativeTemplateFiles`
  - Move native related files to this method.
-  Reorg directory structure:
  - Moved `bin/templates/project` to `templates/project`

### Testing

- `npm t`
- standard `platform add`
- CordovaLib symlinked `platform add`

### Checklist

- [x] I've run the tests to see all new and existing tests pass

### CODE REVIEW

**Comment by erisu** [comment]
I am currently not sure why it is failing. I am able to run the testst locally and build a project without issues.

**Review by raphinesse — COMMENTED** [review]
I reviewed the first four commits and the changes are good!

I suggest we merge these changes as part of #1193 and rebase the rest on top of that. This would focus this PR on reorganization of the repo's file structure.

**Comment by erisu** [comment]
Conflicted and broken will redo the entire PR from scratch Monday.

**Comment by raphinesse** [comment]
I did some further cleanup when reviewing the remaining changes. I'll post that as a new PR ASAP. Hopefully tomorrow. So no need to redo this one for now.

**Pull request closed without merging**
