### PR TITLE
CB-12966: (ios) Fix bug by escaping project name in podfile template

### PR DESCRIPTION
**Pull request by joshdholtz**
### Platforms affected
- iOS

### What does this PR do?
- Fixes a bug when the project name has a single quote in it that caused the `Podfile` to have invalid syntax

### What testing has been done on this change?
- Just manual testing on my own project. I am not familiar with how to write a proper tests for this change 😔  I know I need to add something in `Podfile.spec.js` but not exactly sure what/how exactly I need to do this. Any suggestions on how to write these tests would be truly appreciated ❤️ 

### Checklist
- [x] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [x] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by renatoalencar** [comment]
I really need this bug fix, did you understand why this is not passing in tests?

**Comment by joshdholtz** [comment]
@renatoalencar I have no idea why the tests are not passing. It seems like other tests aren't passing either. You can use this by doing something like...

```
ionic platform add https://github.com/joshdholtz/cordova-ios.git
```
or
```
cordova platform add https://github.com/joshdholtz/cordova-ios.git
```

**Comment by shazron** [comment]
Not passing the linter:
```
bin\templates\scripts\cordova\lib\Podfile.js: line 93, col 51, Mixed double and single quotes.
bin\templates\scripts\cordova\lib\Podfile.js: line 93, col 59, Mixed double and single quotes.
```
Basically the style for this repo is strings are single quoted. So you would reverse your escaping in line 93

**Comment by joshdholtz** [comment]
@shazron Rebased from master so that the tests and linter actually run and pass now. Also separated out the escaping of single quotes into its own function for better testing and added a tests for that new function. Lemme know if there is anything I need to change to make these changes fit better with the style of this project 🙃

**Comment by shazron** [comment]
We had to pull in new code for the new linter using eslint. Consequently, some files have changed. Can you try rebasing, then running `npm run eslint` to make sure it's all kosher

**Comment by joshdholtz** [comment]
@shazron Rebased and updated coding styles 👌

**Pull request closed without merging**
