### PR TITLE
CB-3360 Set custom User-Agent

### PR DESCRIPTION
**Pull request by sinofool**
Add two configurations to set user agent of webview.
OverrideUserAgent to override UA to the setting value.
AppendUserAgent to append the setting value to default UA.

### CODE REVIEW

**Comment by sinofool** [comment]
Who have write access can have a look at this pull request please?
Thanks

**Comment by shazron** [comment]
Note: will review this for the next release, on the 4.0.x branch. Sorry it's taking so long but we were working on getting the 3.8.0 release out with bug fixes.

**Comment by sinofool** [comment]
Thanks @shazron

**Comment by staugaard** [comment]
Yeah I also need this. :+1:

**Pull request closed without merging**
