### PR TITLE
CB-9690 Can't submit iPad apps to the App Store for iOS 9

### PR DESCRIPTION
**Pull request by macdonst**
Closes something

### CODE REVIEW

**Comment by devgeeks** [comment]
Doesn't that completely opt out of "Slide Over and Split View" ?

**Comment by tripodsan** [comment]
I think this should be revisited, once the multi-tasking support is enabled (CB-9161)

**Comment by macdonst** [comment]
Yes, that is the intention. Comments on the JIRA ticket don't show up in this PR but that is our plan.

**Comment by ptarjan** [comment]
this fixes half of https://issues.apache.org/jira/browse/CB-9729 (can you release a point release with this in it please)?

Also, is the other pList problem a similar fix?

**Pull request merged**
