### PR TITLE
CB-8855 Fix display ios devices with --list

### PR DESCRIPTION
**Pull request by csantanapr**

### CODE REVIEW

**Comment by shazron** [comment]
Seems to work. Pulling in.

**Comment by csantanapr** [comment]
:beer:

**Comment by muratsu** [comment]
:+1: :smile:

**Comment by gpetrov** [comment]
please push new release with this fix

**Comment by gpetrov** [comment]
some addition to this: https://github.com/apache/cordova-ios/pull/140

**Pull request closed without merging**
