### PR TITLE
CB-10530 - App freezes sometimes directly after starting on iOS

### PR DESCRIPTION
**Pull request by shazron**

### CODE REVIEW

**Comment by dpogue** [comment]
:+1: from me. I have not seen the splashscreen hanging bug while testing this branch.

**Comment by mhartington** [comment]
Same here, couldn't get anything to break for me. Thanks!

**Comment by thomasMary** [comment]
Works for me. Thanks

**Comment by csantanapr** [comment]
Thanks @mhartington for testing you were able to recreate very easy in your setup.

**Comment by mindhells** [comment]
Thank you!
this works for me... but still have problems with splashscreen plugin (had to remove it in order to make sure the app initializes well every time).
This is my plugin list now:
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-customurlscheme 4.1.3 "Custom URL scheme"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-inappbrowser 1.2.1 "InAppBrowser"
cordova-plugin-network-information 1.2.0 "Network Information"
cordova-plugin-whitelist 1.2.1 "Whitelist"
cordova-plugin-x-socialsharing 5.0.10 "SocialSharing"
cordova-plugin-x-toast 2.4.2 "Toast"
de.appplant.cordova.plugin.local-notification 0.8.4 "LocalNotification"
ionic-plugin-keyboard 1.0.8 "Keyboard"
phonegap-plugin-push 1.5.3 "PushPlugin"

**Comment by michschu** [comment]
Not having a problem with 
_cordova-plugin-splashscreen 3.1.0 "Splashscreen"_
However
_cordova-plugin-inappbrowser 1.2.1 "InAppBrowser"
cc.fovea.cordova.purchase 4.0.0 "Purchase"_
seem not to work anymore.

Currently no time to provide a test scenario. Anybody having a chance to confirm (or not)?

**Comment by rpayanm** [comment]
:+1:  Works for me.

**Comment by adyz** [comment]
Works for me too

**Comment by mix3d** [comment]
How can we start using this without waiting for an official platform update? Been running into this at work, and the powers that be want it fixed asap.

**Comment by rpayanm** [comment]
@mix3d Based on [this](https://issues.apache.org/jira/browse/CB-10530?focusedCommentId=15149506&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15149506):
`$ cordova platform add https://github.com/shazron/cordova-ios.git#CB-10530`

**Comment by mix3d** [comment]
beautiful. Thanks @rpayanm!

**Comment by stevengill** [comment]
cordova-ios 4.1.0 should be coming out later today. Keep an eye out for the blog post to hit the cordova site.

**Comment by mix3d** [comment]
Thanks @stevengill - I've been checking it daily for almost the last week. Eyes are well peeled.

**Comment by shazron** [comment]
cordova-ios-4.1.0 has been released, thanks to Steve! http://cordova.apache.org/announcements/2016/03/02/ios-4.1.0.html

**Comment by mirko77** [comment]
@shazron @stevengill 

Still not loading on iOS 9.3 (iPad Air 2 ) with Cordova iOS @4.1.0. It gets stuck at splashscreen. Loads fine via Xcode 7.3

steps to reproduce:


`cordova create hello com.example.hello HelloWorld`
`cd hello`
`cordova platform add ios@4.1.0`
'cordova run ios -device'

**Comment by rpayanm** [comment]
Do you test on iOS @4.1.1?
http://cordova.apache.org/announcements/2016/04/04/ios-4.1.1.html

**Comment by mirko77** [comment]
I just did it, same problem, here is the last part of what it logs:

```
(lldb)     command script add -f fruitstrap_939ce68a6e2237a195c4e6ec07744405e8d23685.connect_command connect
(lldb)     command script add -s asynchronous -f fruitstrap_939ce68a6e2237a195c4e6ec07744405e8d23685.run_command run
(lldb)     command script add -s asynchronous -f fruitstrap_939ce68a6e2237a195c4e6ec07744405e8d23685.autoexit_command autoexit
(lldb)     command script add -s asynchronous -f fruitstrap_939ce68a6e2237a195c4e6ec07744405e8d23685.safequit_command safequit
(lldb)     connect
(lldb)     run
success
(lldb)     safequit
```

**Comment by shazron** [comment]
What you are encountering is a separate issue with ios-deploy. Make sure you have the latest, version 1.8.6

**Comment by mirko77** [comment]
Great, with ios-deploy 1.8.6 it is working fine.

**Pull request closed without merging**
