### PR TITLE
CB-9883

### PR DESCRIPTION
**Pull request by purplecabbage**
Also remove the wk-webview bridge as the plugin itself simply clobbers cordova.exec now.
1 Bridge! You shall not pass!

### CODE REVIEW

**Comment by shazron** [comment]
It's the Bridge of IFrame-Dûm! Good work Olórin of the Cabbages Purple

**Comment by chaffeqa** [comment]
I don't know if this was the path intended, but the new changes break the falling back to UIWebView since simply including the WKWebview clobbers `cordova.exec` (and the browser proceeds to barf on a non-existent object on `window.webkit.messageHandler` when running via the UIWebView)

Understandable if this is simply a move away from falling back to UIWebView, but my understanding was that you would still gracefully degrade support to UIWebView (for instance if iOS 8 and not using local webserver)

**Comment by shazron** [comment]
Good point, didn't think of that scenario. Ideally each WebView engine, when activated, should inject its own bridge. This would solve this scenario. 

We could do this for the WKWebViewEngine plugin -- when it is activated, read the .js file and inject it. The UIWebViewEngine (private) plugin could do it as well in the same manner but we would have to remove the .js from cordova-js-src folder (which is aggregated by cordova-js to create cordova.js) and leave this as a concern for the platform itself.

**Comment by purplecabbage** [comment]
I'll fix that.

**Comment by purplecabbage** [comment]
Is this sufficient in the wkwebview plugin?
```
if(window.webkit && window.webkit.messageHandler) {
    module.exports = iOSExec;
}
else {
    // this will end up clobbering cordova.exec with cordova.exec
    // a special case for falling back to UIWebView
    module.exports = cordova.exec; 
}
```
It will prevent the clobber in this case.

**Comment by chaffeqa** [comment]
That looks great to me! honestly i dont know how i felt about the idea of dynamically injecting a script... call me old school ;)

Thanks guys a ton for all the hard work on this platform! super appreciated!

**Comment by purplecabbage** [comment]
Are you able to verify this works @chaffeqa?

**Pull request closed without merging**
