### PR TITLE
feat: add optional compile-time decision for disabling UIWebView

### PR DESCRIPTION
**Pull request by jcesarmobile**
Based on https://github.com/apache/cordova-ios/pull/662, updated the prepare script to also modify the CordovaLib project so no removing and re adding platform is needed when `<preference name="WKWebViewOnly" value="true" />` was added to the `config.xml` after the platform was added.
Also makes it possible to unset the value, the implementation on https://github.com/apache/cordova-ios/pull/662 didn't allow to change the value back to 0 without removing the platform. 

I added the modified platform and submitted to App store and got the warning, then added `<preference name="WKWebViewOnly" value="true" />`, ran `cordova prepare ios`, submitted again and didn't get the warning. 

closes: #662

### CODE REVIEW

**Comment by rajashekaranugu** [comment]
@jcesarmobile Can you please explain us clearly the steps you followed.

we also used to get the warning email from apple when we used ionic3, cordova 8.1.2, but currently we have updated our app to IONIC4 and Cordova 9.0.0 (did't deploy app to store yet with updated framework)

**Is just adding "<preference name="WKWebViewOnly" value="true" />" enough in our config.xml. Am not clear how to clone this repo. Please explain any other steps involved, so that I will also give a try**


Below is the IONIC INFO:

Ionic:

   ionic (Ionic CLI)  : 4.5.0
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 21 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 6.10.1
   OS         : macOS Mojave
   Xcode      : Xcode 11.2.1 Build version 11B500.


Thanks for your time

**Comment by jcesarmobile** [comment]
you have to clone the repository 
`git clone https://github.com/jcesarmobile/cordova-ios`
then go to the cloned folder
`cd cordova-ios`
then check the branch where I committed the changes
`git checkout conditional-webview`
then check the path to the folder where you cloned cordova-ios
`pwd`
use the result of that command to install cordova-ios into your project
(from your app project)
`cordova platform add (result from pwd here)`

Now if you add `<preference name="WKWebViewOnly" value="true" />` to the `config.xml` and run `cordova prepare ios` the UIWebView conde will be hidden by at build time, so you need a wkwebview plugin installed or your app won't work.

**Comment by rajashekaranugu** [comment]
> you have to clone the repository
> `git clone https://github.com/jcesarmobile/cordova-ios`
> then go to the cloned folder
> `cd cordova-ios`
> then check the branch where I committed the changes
> `git checkout conditional-webview`
> then check the path to the folder where you cloned cordova-ios
> `pwd`
> use the result of that command to install cordova-ios into your project
> (from your app project)
> `cordova platform add (result from pwd here)`
> 
> Now if you add `<preference name="WKWebViewOnly" value="true" />` to the `config.xml` and run `cordova prepare ios` the UIWebView conde will be hidden by at build time, so you need a wkwebview plugin installed or your app won't work.

Thanks for the response will try it and will let you know

**Comment by l3ender** [comment]
This is a great change--thanks for it. Should it be added to readme for more visibility?

**Comment by l3ender** [comment]
Also, I see the 5.1.0 release hasn't made it to npm registry yet. Is there anything I can do to help with this?

**Comment by jcesarmobile** [comment]
It’s in the Apache release process at the moment, will take a few days to be released if everything goes fine.

**Comment by jcesarmobile** [comment]
it's released now https://cordova.apache.org/announcements/2019/11/25/cordova-ios-release-5.1.0.html

**Comment by wilsolutions** [comment]
> it's released now https://cordova.apache.org/announcements/2019/11/25/cordova-ios-release-5.1.0.html

Hi, please, does this release change anything in your comment here?
https://github.com/apache/cordova-discuss/pull/110#issuecomment-558144479

**Comment by jcesarmobile** [comment]
Don't really understand the question

**Comment by webb24h** [comment]
> Based on #662, updated the prepare script to also modify the CordovaLib project so no removing and re adding platform is needed when `<preference name="WKWebViewOnly" value="true" />` was added to the `config.xml` after the platform was added.
> Also makes it possible to unset the value, the implementation on #662 didn't allow to change the value back to 0 without removing the platform.
> 
> I added the modified platform and submitted to App store and got the warning, then added `<preference name="WKWebViewOnly" value="true" />`, ran `cordova prepare ios`, submitted again and didn't get the warning.
> 
> closes: #662

Oh wow you sir did surely save my life! This works and no more warning in the email!

**Pull request merged**
