### PR TITLE
(iOS) Dark mode splashscreen storyboard images

### PR DESCRIPTION
**Pull request by terreng**
This is my first pr so please don't burn me at the stake. 

### Platforms affected

iOS

### Motivation and Context

I wanted to include a dark mode variant of my app's splash screen, but found that Cordova did not yet support this feature. It turns out that it only took a few lines of code, so I figured I'd share it here.

I found this related issue: https://github.com/apache/cordova-plugin-splashscreen/issues/246. It turns out that no changes to the splashscreen plugin are necessary to make it happen.

### Description

This enables dark mode storyboard images by allowing you to specify splash images based on appearance (dark or light). It checks for ~dark or ~light suffixes in splash images. If neither is found, they're used as the default. It then adds the variants to Contents.json, and the rest is handled by iOS. Example config.xml:

`<splash src="res/screen/ios/Default@3x~iphone~comany.png" />`
`<splash src="res/screen/ios/Default@3x~iphone~comany~dark.png" />`

This pr only adds support for iOS.

### Testing

I've tested these changes on an iPhone and everything appears to work as intended. I've updated existing tests and added new ones as appropriate, and all tests pass.

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

Documentation would need to change over at https://github.com/apache/cordova-plugin-splashscreen/blob/master/README.md.

Thank you.

### CODE REVIEW

**Comment by NiklasMerz** [comment]
@terreng Thank you for your first PR 🥇  This is a great feature. Please check the Travis log, if you can turn the tests green, review is much easier.

Looks like some tests need to be changed and/or new tests are needed.

**Comment by breautek** [comment]
Thank you for your PR. Just a couple notes, not exactly related to this PR, but when making PRs in general.

> I haven't run any tests

You can run local tests on your machine by running `npm test`. This will help catch some problems (such as your eslint error :stuck_out_tongue_winking_eye: ) 

I also noticed that you made changes in your fork's master branch for your PR. I would recommend always creating a new branch for your PRs to keep your master branch clean. This isn't a problem right now, but could be later. If you add more commits to your master (maybe for a different PR) those commits will end up in this PR as well and that would not be very desirable.

Regarding this PR specifically, I think everything looks good and I'm happy you considered making specifying the appearance optional, which also helps maintain backwards compatibility. As soon as the checks turn green I'll give my :+1:

**Comment by terreng** [comment]
Alright, I've updated the failed tests and added three new ones.

**Comment by NiklasMerz** [comment]
I think documentation how to use this feature should be part of this PR, too.

**Comment by terreng** [comment]
Documentation would have to change for cordova-plugin-splashscreen which isn't a part of this repo.

**Comment by NiklasMerz** [comment]
Good point. I got confused that the code is part of cordova-ios and not the plugin.

**Pull request merged**
