### PR TITLE
refactor: replace copy-www-build-step script with build phase

### PR DESCRIPTION
**Pull request by NiklasMerz**
### Platforms affected
iOS and Mac (Catalyst)

### Motivation and Context

We could move the build step of copying the www directory and config.xml to the Xcode "Copy files" commands to avoid issues from the manual script like changed paths or different paths between iOS and macOS.

See #699

### Description

**Up for discussion.**

Some links: https://github.com/apache/cordova-ios/issues/699#issuecomment-645119408

This is probably the most important reason for the script: https://issues.apache.org/jira/browse/CB-5397?focusedCommentId=13859057&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13859057

### Testing

* Run iOS simulator from CLI
* Run iOS simulator from Xcode
* Run Mac (designed for iPad) from Xcode
* Enable and run Mac natively (M1) from Xcode 

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by NiklasMerz** [comment]
Fixed now. Good to know why they are there.

I should have checked the diff again. These Xcode files are tricky.

**Comment by NiklasMerz** [comment]
@dpogue How did you test that? What's the best way to reproduce this?

I did quick tests and this www folder and config.xml look like the right one. I changed them to **__Project_NAME/..** but then plugins won't work anymore because cordovas js files are missing.

My test:

- Change index.html, build ios, run app on mac and ios sim -> see changes
- Change index.html in config.xml, build ios, run mac and ios sim from Xcode -> page cannot load

To me this looks like the right files get copied into the app.

**Comment by dpogue** [comment]
hmm, I was testing this as part of https://github.com/apache/cordova-ios/pull/1162 (which used this as a starting point) and getting "Connecting to device..." in the simulator, and log messages about the Console plugin not being found.

This should work to reproduce:
```
npx cordova@nightly create xcodeTestApp
cd xcodeTestApp
npx cordova@nightly platform add github:apache/cordova-ios#xcode-copy
open platforms/ios/HelloCordova.xcworkspace
# Run the app in a simulator from Xcode
```

**Comment by NiklasMerz** [comment]
Interesting side fact. I just tried to run the osx platform on the M1 mac with this PR https://github.com/apache/cordova-osx/pull/105 and got the same error:

`ERROR: Plugin 'Device' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
`

**Review by dpogue — APPROVED** [review]
I've tested this (including with Catalyst) and it is working as expected. Also tested with cordova-plugin-device added, and was able to print out device information.

**Review by NiklasMerz — COMMENTED** [review]
Thanks @erisu for completing this and your good explanation. It's working as espected for me as well with all Mac configurations and an iOS simulator.

**Pull request merged**
