### PR TITLE
CB-7428: Enable Swift development of Plugins

### PR DESCRIPTION
**Pull request by cjpearson**
I've included the changes listed under CB-7428 into the template projects. As part of these changed, I've moved up the minimum deployment target to iOS 7.0 ( a requirement for Swift.) It's also been over a year since iOS 5 support was dropped. I've been testing with this [example plugin](https://github.com/edewit/cordova-plugin-hello/tree/swift).  With these changes you can now add Swift plugins without changing any settings in Xcode.

### CODE REVIEW

**Comment by shazron** [comment]
I know the change is due, but this requires more than a pull request. I've brought it up before (over half a year ago) so it might be time to bring it up again in the dev mailing list.

For now, for Swift support, you can follow how this was done by using a plugin hook: https://issues.apache.org/jira/browse/CB-8254

**Comment by cjpearson** [comment]
Thanks for the feedback, Shazron. I wasn't sure how it should be brought up, I just wanted to get the ball rolling somehow.

**Comment by shazron** [comment]
Thanks for the reminder, I've posted a new thread to get consensus: http://callback-dev.markmail.org/thread/c7c3iiuy6hr54pf6

**Comment by shazron** [comment]
Also https://issues.apache.org/jira/browse/CB-8643

**Comment by shazron** [comment]
Hi @cjpearson - I'd like this to get in sooner rather than later. Since CB-8643 has been resolved, this can be merged in. I see a Connor Pearson listed as someone that has already signed the Apache iCLA, confirming this is you?

**Comment by cjpearson** [comment]
That's correct. Thanks, @shazron.

**Comment by shazron** [comment]
PR merged into 4.0.x branch, see above commit reference and CB-7428

**Comment by ephemer** [comment]
@shazron how can I test the 4.0.x branch ? cordova platform update ios@4.0.0 doesn't work - is there another way using the CLI? or what's the best way to do this?

**Comment by dpogue** [comment]
`cordova platform add ios@4.0.x --usegit`

**Comment by ephemer** [comment]
@dpogue thank you!

**Comment by ephemer** [comment]
@dpogue I was able to install the new version using `cordova platform update ios@4.0.x --usegit` – that didn't seem to update my CordovaLib though (which would include the swift bridging header etc).

Any ideas, other than `cordova platform remove ios` and adding it again? My cordova build comes from a meteor project, so if I do that, I lose all the customisation that meteor adds. I can't see a way of telling meteor which cordova iOS platform version to use.

**Comment by shazron** [comment]
Auto-closing since it has been merged.

**Pull request closed without merging**
