### PR TITLE
fix(ios): split xcode project location by env separator

### PR DESCRIPTION
**Pull request by SvyatoslavPozhydaev**
### Platforms affected
ios

### Motivation and Context

fixes https://github.com/apache/cordova-ios/issues/1139

### Description

replaced the delimiter string with the environment delimiter

### Testing

I've tested this code on install cordova plugin like `scandit-cordova-datacapture-core`

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

### CODE REVIEW

**Review by breautek — APPROVED** [review]

**Comment by breautek** [comment]
Closing/reopening cause idk why checks didn't run.

**Review by NiklasMerz — APPROVED** [review]
LGTM

**Review by PieterVanPoyer — APPROVED** [review]
LGTM

**Comment by breautek** [comment]
Thanks for the reviews and thank you @SvyatoslavPozhydaev for your effort into preparing this PR.

**Pull request merged**
