### PR TITLE
CB-10962 CB-10945 removes justlaunch flag waiting for a fix in ios-deploy

### PR DESCRIPTION
**Pull request by akofman**

### CODE REVIEW

**Comment by omefire** [comment]
This works, but it brings us back to when we used to have to exit lldb manually.

**Comment by omefire** [comment]
I'd prefer this PR be merged into ios-deploy: https://github.com/phonegap/ios-deploy/pull/218
That way, we wouldn't have to fix this issue here.

**Comment by akofman** [comment]
Sure I 100% agree with that. That's why I asked to @shazron what he thinks. If we have to wait 6 months more, I think it's better to keep something working instead of the actual situation.

**Comment by omefire** [comment]
The thing is that this used to work just fine. Some recent changes might have broken it.

**Comment by akofman** [comment]
Maybe it's related to the last XCode updates. What version are you using ?

**Comment by omefire** [comment]
I'm using XCode Version 7.3 (7D175)

**Comment by omefire** [comment]
I tested the following PR: https://github.com/phonegap/ios-deploy/pull/218
and unfortunately, it didn't fix the issue for me.

**Comment by akofman** [comment]
hmmmm indeed.

**Comment by omefire** [comment]
Could it be XCode update(from 7.2 to 7.3) that is causing this issue ?

**Comment by akofman** [comment]
I think it's more than possible.

**Comment by akofman** [comment]
XCode 7.2 is using lldb-340.4.119.1 while XCode 7.3 is using lldb-350.0.21.3.

**Comment by omefire** [comment]
Hmmm, interesting

**Comment by omefire** [comment]
I think we should pull this in, while waiting for a fix for the XCode 7.3 issue. What do you think @shazron ?

**Comment by shazron** [comment]
This change will modify expected behaviour if someone is scripting this, since the run call will not terminate. That is, however, a lower priority consequence versus fixing this bug right now. I'll investigate a fix for ios-deploy for today, if there is no progress, we should proceed with this change.

**Comment by omefire** [comment]
OK, sounds good. I'm running some investigations as well.

**Comment by shazron** [comment]
Update (good news?): https://github.com/phonegap/ios-deploy/pull/218#issuecomment-206597622

**Comment by shazron** [comment]
Everyone, try the new ios-deploy version 1.8.6.
This PR can be closed.

**Pull request closed without merging**
