### PR TITLE
CB-8435 enable jshint for iOS platform

### PR DESCRIPTION
**Pull request by muratsu**
- Created a npm run jshint command & integrate into npm run test
- Created jshint rules files for spec and rest of the repo
- Fixed all jshint issues

### CODE REVIEW

**Comment by muratsu** [comment]
`node node_modules/jshint/bin/jshint bin && node node_modules/jshint/bin/jshint tests` is passing. Failing tests are not related to this PR

**Comment by purplecabbage** [comment]
The failing test is because your 'end-to-end list validation handles list parameter' test requires ios-sim which is not installed.
Installation of ios-sim should be added to .travis.yml if this is an important test.

**Comment by muratsu** [comment]
Seems like an artifact. The original design changed and that checkin was supposed to be reverted. I'll take a look

**Comment by muratsu** [comment]
The issue is finally resolved -  we can go forward with this PR

**Comment by shazron** [comment]
It should be CB-8435 (please edit the PR title). Don't worry about the commits, I can edit the commit message when pulling/squashing it in.

**Comment by shazron** [comment]
pulled in (see CB-8435). you can close this issue now

**Comment by muratsu** [comment]
Thanks!

**Pull request closed without merging**
