### PR TITLE
generates a workspace instead of subproject

### PR DESCRIPTION
**Pull request by edewit**
Initial part of [CB-5921](https://issues.apache.org/jira/browse/CB-5921)

### CODE REVIEW

**Comment by edewit** [comment]
now that swift options are added is this still relevant?

**Comment by yjukaku** [comment]
@edewit Can you please clarify what you mean? To be able to use CocoaPods, we still need a workspace to be generated instead of a project with a sub-project.

**Comment by edewit** [comment]
The initial idea was to be able to support swift plugins. This is now fixed by changing build.xconfig. For cocoapods this pr could still be relevant

**Comment by purplecabbage** [comment]
cordova-ios has supported workspaces+cocoapods for awhile now.  Somehow this was never closed.  Thanks for contributing.

**Pull request closed without merging**
