### PR TITLE
CB-9254 copy over templates/PROJECT_NAME/Classes during cordova platf…

### PR DESCRIPTION
**Pull request by stevengill**
…orm update

### CODE REVIEW

**Comment by stevengill** [comment]
discussion: https://issues.apache.org/jira/browse/CB-9254

**Comment by stevengill** [comment]
Chatted with Shaz. Going to update this PR to do most of the steps create does during update. Safest way

**Comment by stevengill** [comment]
Okay, updated the PR. Take a look @shazron

**Comment by shazron** [comment]
Besides the plist/package.json changes, LGTM

**Comment by stevengill** [comment]
They local urls get auto added. I believe it is harmless. It got changed when I made plist a top level dependency due to needing it for bin/lib/create.js

**Comment by shazron** [comment]
This PR didn't close even though the commits are in. Might have to do a future empty commit to close this one.

**Comment by stevengill** [comment]
Done

**Pull request closed without merging**
