### PR TITLE
[WIP] ci(AppVeyor): add Node.js 12

### PR DESCRIPTION
**Pull request by brodybits**

### CODE REVIEW

**Comment by brodybits** [comment]
Looks like there was a spurious failure on Travis CI, which is not changed in this PR, just restarted the Travis CI.

**Comment by brodybits** [comment]
I don’t understand this: there is still a build failure on Travis CI, even though I didn’t touch it. ???

**Comment by janpio** [comment]
(Looking into it)

**Comment by janpio** [comment]
Not one of the obvious cases I encountered while working on plugin CI in the last few weeks unfortunately. But it happens quite often that Travis or someone else in the chain changes something so builds just fail :/ Best verify via a second PR that just adds an empty line or similar. Very possible it currently is just broken.

**Comment by erisu** [comment]
Closing as it is already in master.

**Pull request closed without merging**
