### PR TITLE
CB-9827 Implement and expose PlatformApi for iOS

### PR DESCRIPTION
**Pull request by sgrebnov**
https://issues.apache.org/jira/browse/CB-9827

* Prepare and plugin management functionality has been moved from Lib to platform-ios
* Includes cordova-common
* Replaced console.log w/ corresponding events.emit calls
* I tried to reduce changes and keep files/logic as-is to simplify code review

Tested using mobile-spec (also compared generated mobilespec app w/ original one using diff tool to ensure correctness)

### CODE REVIEW

**Comment by sgrebnov** [comment]
Re-based work on top of master and grouped all changes into two commits:
1. 6347263c80e4257506a77cece832c4c63c353145 contains implementation/changes
2. b4dd1e0bbd5bdbca3ef0bfd1561baedf38ccedaa just adds required node modules

**Comment by omefire** [comment]
I'll take a stab at reviewing this.

**Comment by sgrebnov** [comment]
TODO: @sgrebnov to rebase on top of master, fetch latest changes from cordova-lib (preferences handling change, may be more), address Mefire notes

**Comment by omefire** [comment]
Instead of relying on 'nopt' default value for its constructor, why don't we explicitly use: 'process.args' here ?
Something like:

``` 
var argv = require('nopt') ({
    'help' : Boolean,
    'cli' : Boolean,
    'shared': Boolean,
    'link' : Boolean
}, process.argv)```

**Comment by omefire** [comment]
what about the ```cli``` option? It also needs to be sent forward.

**Comment by shazron** [comment]
What do you guys think of merging this in for cordova-ios 4.0 release? I'm still working on CB-7287 mobile-spec failures (3) for WKWebView, but the platform is almost good to go.

**Comment by vladimir-kotikov** [comment]
No objections from my side. The PR has passed internal review, all CR notes has been addressed. @sgrebnov?

**Comment by sgrebnov** [comment]
+1

**Comment by shazron** [comment]
I've already pulled in this change, it's in the Apache git repos and somehow it hasn't mirrored yet: https://git1-us-west.apache.org/repos/asf?p=cordova-ios.git;a=commit;h=26cca47e3c1fa85f9f06232bfe099f9d4c9c8e40

**Comment by shazron** [comment]
FYI there was one issue that wasn't caught, Steve fixed it:
https://git-wip-us.apache.org/repos/asf?p=cordova-ios.git;h=b89cd71

When doing a 'cordova prepare' the version of the platform was printed to stdout.

**Comment by shazron** [comment]
Another issue I found: https://issues.apache.org/jira/browse/CB-10063?focusedCommentId=15041424&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15041424

this.pbxproj is not defined. I have to pass in "locations" to handleBuildSettings to get pbxproj.

**Pull request closed without merging**
