### PR TITLE
Add CDVWebViewEngineConfigurationDelegate to expose the WKWebViewConfiguration

### PR DESCRIPTION
**Pull request by msmtamburro**
### Platforms affected

iOS

This can be merged after https://github.com/apache/cordova-ios/pull/1272

### Motivation and Context

CDVWebViewEngine needs a way to set the websiteDataStore of its configuration.

Fixes:
https://github.com/apache/cordova-ios/issues/900

### Description

Adds and exposes a protocol, CDVWebViewEngineConfigurationDelegate, which allows access to the configuration.

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by dpogue** [comment]
The `CDVWebViewEngineConfigurationDelegate` work has already been merged to master, and the extra commits make it quite hard to see what the actual change is here.

Can you rebase so that this includes only the commit related to data storage?

**Comment by msmtamburro** [comment]
P.ImprintUniqueID {
	MARGIN: 0cm 0cm 0pt
}
LI.ImprintUniqueID {
	MARGIN: 0cm 0cm 0pt
}
DIV.ImprintUniqueID {
	MARGIN: 0cm 0cm 0pt
}
TABLE.ImprintUniqueIDTable {
	MARGIN: 0cm 0cm 0pt
}
DIV.Section1 {
	page: Section1
}








Yes! Just lost my access to push changes from work, so it may be a while. 




From: "Darryl Pogue" ***@***.***>
Date: Saturday, October 2, 2021 at 2:34:17 PM
To: "apache/cordova-ios" ***@***.***>
Cc: "Tamburro, Michael (WM Technology)" ***@***.***>, "Author" ***@***.***>
Subject: Re: [apache/cordova-ios] Issue 900 website data store (#1157)




The CDVWebViewEngineConfigurationDelegate work has already been merged to master, and the extra commits make it quite hard to see what the actual change is here.
Can you rebase so that this includes only the commit related to data storage?
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
Triage notifications on the go with GitHub Mobile for 
iOS or 
Android. 



NOTICE: 
Morgan Stanley is not acting as a municipal advisor and the opinions or views 
contained herein are not intended to be, and do not constitute, advice within 
the meaning of Section 975 of the Dodd-Frank Wall Street Reform and Consumer 
Protection Act. If you have received this communication in error, please destroy 
all electronic and paper copies and notify the sender immediately. 
Mistransmission is not intended to waive confidentiality or privilege. Morgan 
Stanley reserves the right, to the extent required and/or permitted under 
applicable law, to monitor electronic communications, including telephone calls 
with Morgan Stanley personnel. This message is subject to the Morgan Stanley 
General Disclaimers available at the following link: 
http://www.morganstanley.com/disclaimers.  If you cannot access the links, 
please notify us by reply message and we will send the contents to you. By 
communicating with Morgan Stanley you acknowledge that you have read, understand 
and consent, (where applicable), to the foregoing and the Morgan Stanley General 
Disclaimers.You may have certain rights regarding the information that 
Morgan Stanley collects about you. Please see our Privacy Pledge 
https://www.morganstanley.com/privacy-pledge for more information about your 
rights.

**Comment by globules-io** [comment]
@msmtamburro was this pull request final? Still marked as Draft? Is this pull request fully working ?

**Comment by msmtamburro** [comment]
> @msmtamburro was this pull request final? Still marked as Draft? Is this pull request fully working ?

Sorry for the delay--this is up-to-date.  There's a related PR that should be merged right after this one: https://github.com/apache/cordova-ios/pull/1051

**Comment by msmtamburro** [comment]
Sorry it took so long to get back to you on this, but good news: nothing to do here.  The commits in this PR safely made it to master in an earlier PR.  I'll close this, and the associated issue.

**Pull request closed without merging**
