### PR TITLE
(chore): update dependencies for minor release

### PR DESCRIPTION
**Pull request by NiklasMerz**
### Platforms affected
iOS

### Motivation and Context

Working through the release process I found some outdated dependencies:

```
Package       Current  Wanted  Latest  Location
find-process    1.4.3   1.4.4   1.4.4  cordova-ios
fs-extra        9.0.1   9.1.0   9.1.0  cordova-ios
ios-sim         8.0.2   8.0.2   9.0.0  cordova-ios
jasmine         3.5.0   3.5.0   3.6.4  cordova-ios
nopt            4.0.3   4.0.3   5.0.0  cordova-ios
semver          7.3.2   7.3.4   7.3.4  cordova-ios
tmp             0.1.0   0.1.0   0.2.1  cordova-ios
```

### Description

I updated dependencies and found no issues locking at the release notes and test results. They should fit in this minor release.

Some packages turned tests red and are major upgrades. I created an issue for the next version: https://github.com/apache/cordova-ios/issues/1068

### Testing

Tests and CI

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Review by breautek — APPROVED** [review]
Notable changes:

## [find-process@1.4.4](https://github.com/yibn2008/find-process/blob/master/HISTORY.md)
- :heavy_check_mark:  Security patch for Windows users

## [tmp@0.2.1](https://github.com/raszi/node-tmp/blob/master/CHANGELOG.md)
- :heavy_check_mark: Resolves an issue where `tmp` will `process.exit` itself.

## [fs-extra@9.1.0](https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md)
- :heavy_check_mark: Performance improvements

## [nopt@5.0.0](https://github.com/npm/nopt/blob/master/CHANGELOG.md)

Haven't maintained a changelog since version 4.0.1. Upgrading a major without knowing what has changed is a bit sketchy, but their `package.json` says they support >= node 6. I suppose as long as our tests passes then we are still ok.

## [semver@7.3.4](https://github.com/npm/node-semver/blob/master/CHANGELOG.md)

Haven't maintained a changelog since version 7.3.0. Patch increments should be okay.

**Comment by NiklasMerz** [comment]
Thanks @breautek for the summary.

Regarding `nopt`: Seems like they just did a small dependency update: https://github.com/npm/nopt/compare/v4.0.3...v5.0.0

**Comment by jcesarmobile** [comment]
In the comment you say wanted 4.0.3 but updated to 5.0.0.
Also says “minor and patch” but that’s major.

Not saying we shouldn’t update to 5.0.0, only that the description is confusing.

**Comment by NiklasMerz** [comment]
NPM outdated wanted 4.0.3. Since I did not find dangerous changes in 5.0.0 (see previous comment) I updated to the latest version.

5.0.0 looks save but I can revert that.

**Comment by jcesarmobile** [comment]
Just saying that the PR change doesn’t do what you say it does in the or description, you can just update the description

**Review by erisu — APPROVED** [review]
LGTM

**Review by jcesarmobile — APPROVED** [review]

**Comment by NiklasMerz** [comment]
Thank you all for the feedback

**Pull request merged**
