### PR TITLE
CB-9453 Updating to iOS@3.9.0 not building

### PR DESCRIPTION
**Pull request by daserge**
[Jira issue](https://issues.apache.org/jira/browse/CB-9453)

### CODE REVIEW

**Comment by stevengill** [comment]
Thanks for getting to this so quickly @daserge!

**Comment by stevengill** [comment]
I tested it by merging it into the 3.9.x branch. It works.

**Comment by stevengill** [comment]
I say lets merge it in so I can get a patch release for this going.

**Comment by csantanapr** [comment]
I just finish testing this and it also works for me

cordova platform add ios
cordova build
cordova platform update ../cordova-ios-CB9453/
cordova build
cordova emulate

**Pull request merged**
