### PR TITLE
Cocoapods support improvement, using podspec tag in plugin.xml

### PR DESCRIPTION
**Pull request by knight9999**
### Platforms affected
ios

### What does this PR do?
- Cocoapods Support Improvement
- Support Custom Cocoapods Repository
- Added Test Code

See https://github.com/apache/cordova-discuss/pull/108

The following PR is needed to be merged first
https://github.com/apache/cordova-common/pull/48

### What testing has been done on this change?

-  Local Plugin Test (`cordova plugin add` which uses `podspec` tags to local PC)
- `npm run test`

Because this PR depends on PR (https://github.com/apache/cordova-common/pull/48), the test fails without editing package.json.
With modified package.json, both the travis and appveyor tests passes.

- (Source) https://github.com/cordova-develop/cordova-ios/commits/dev_improve_cocoapod_support_test
- https://ci.appveyor.com/project/knight9999/cordova-ios/build/1.0.40
- https://travis-ci.org/cordova-develop/cordova-ios/builds/432766497?utm_source=github_status&utm_medium=notification

### Checklist
- [x] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by shazron** [comment]
Thanks @knight9999 but the builds are failing:
```
npm run unit-tests
> cordova-ios@5.0.0-dev unit-tests C:\projects\cordova-ios
> jasmine --config=tests/spec/unit.json
module.js:478
    throw err;
    ^
Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (module.js:476:15)
```

**Comment by knight9999** [comment]
@shazron Thanks for testing, and I am sorry to trouble you.
This PR depends other PR apache/cordova-common#48.
Therefore please change package.json as follows only for testing.
```
diff --git a/package.json b/package.json
index 4ce47fc9..bc7cd729 100644
--- a/package.json
+++ b/package.json
@@ -51,12 +51,13 @@
   },
   "engineStrict": true,
   "dependencies": {
-    "cordova-common": "2.1.0",
+    "cordova-common": "https://github.com/cordova-develop/cordova-common.git#dev_improve_cocoapod_support",
     "ios-sim": "^6.1.2",
     "nopt": "^3.0.6",
     "plist": "^1.2.0",
     "q": "^1.4.1",
     "shelljs": "^0.5.3",
+    "unorm": "^1.4.1",
     "xcode": "^0.9.0",
     "xml-escape": "^1.1.0"
   },
```

**Comment by knight9999** [comment]
I have rebased master. 
The above comments are also updated. 
For tests, only `cordova-common` in `package.json` should be edited.

**Comment by shazron** [comment]
Thanks! This can be reviewed and tested, but can't be accepted to be merged until the production release of cordova-common that has the changes needed is out for final testing. 

We've had this situation before, and we just had to wait until the dependency is updated in npm. Thus, let us try to get cordova-common that has these dependent changes out for a new release, then we update this PR.

**Comment by knight9999** [comment]
@shazron Thanks a lot.
It's exactly as you said.  We have to wait until the dependency is updated.
I think waiting is OK.

**Comment by knight9999** [comment]
Sorry, I update this PR to fix the issue that the swift-version in CocoaPods is reset when adding other CoacoaPods plugin.

**Comment by erisu** [comment]
@janpio common 3 had been released and master's package.json had been bumped. 
Additional, the PR had been rebased and tests are all green. I believe we can remove the block.

**Pull request merged**
