### PR TITLE
CB-12856 - Skip CocoaPods check_reqs if on non-darwin (macOS) platform

### PR DESCRIPTION
**Pull request by shazron**
**WORK IN PROGRESS**

### Platforms affected

self

### What does this PR do?

Ignore CocoaPods check and installation on non-darwin (macOS) platforms.

### What testing has been done on this change?

Work In Progress. No testing has been done yet, pending.

### Checklist
- [X] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [X] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [ ] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by shazron** [comment]
Tested on macOS Sierra 10.12.5:
- [X] CocoaPods not installed, should output error to install it
- [X] CocoaPods not synced, should output error to `pod sync`
- [X] Once installed, made sure it built for device properly

Tested on Windows 10:
- [ ] CocoaPods not installed, should **not** output error to install it
- [ ] CocoaPods not synced, should **not** output error to `pod sync`

Tested on Linux:
- [ ] CocoaPods not installed, should **not** output error to install it
- [ ] CocoaPods not synced, should **not** output error to `pod sync`

**Comment by shazron** [comment]
Tested using
```
cordova platform add https://github.com/shazron/cordova-ios.git#CB-12856
cordova plugin add https://github.com/phonegap/phonegap-plugin-push.git --verbose
```

**Comment by shazron** [comment]
Array.includes failure on node 4 when on Windows. I will have to re-test everything again -- this means also that the check_reqs is not covered in the unit-tests (which do test on nodes 4 and 6), unit-tests are missing.

**Comment by shazron** [comment]
CI all green, and my tests below all succeed. Squashing.

Tested on macOS Sierra 10.12.5 (node 4, 6): SUCCESS
- [X] CocoaPods not installed, should output error to install it
- [X] CocoaPods not synced, should output error to `pod sync`
- [X] Once installed, made sure it built for device properly

Tested on Windows 10 (node 4, 6): SUCCESS
- [X] CocoaPods not installed, should **not** output error to install it
- ~[ ] CocoaPods not synced, should **not** output error to `pod sync`~

Tested on Linux (Ubuntu 16, node 4, 6): SUCCESS
- [x] CocoaPods not installed, should **not** output error to install it
- ~[ ] CocoaPods not synced, should **not** output error to `pod sync`~

**Comment by Sroose** [comment]
hello, any idea when this fix will be released?

**Comment by andreszs** [comment]
**Installs version 1.10.5 under Windows 8.1 on July 2017 and gets CocoaPods error: tries to install the non-existant _CocoaPods for Windows_.**

Seriously people, is it really that hard to find out the user's platform? I bet that Cordova provides some kind of global platform variable, it should be x64 for Windows 8 64 bits. For charity, please avoid misleading developers with stupid error messages that are totally out of place.

**Comment by fredgalvao** [comment]
@andreszs Did you try:
```
cordova platform add https://github.com/shazron/cordova-ios.git#CB-12856
cordova plugin add https://github.com/phonegap/phonegap-plugin-push.git --verbose
```
?

If you did that, and the issue was **not Resolved**, then we should review the issue. Otherwise, we just need to wait for a new release to contain this fix.

**Comment by filmaj** [comment]
@andreszs I would also recommend toning down your entitlement-based outrage for a _free_ open source software. There's so much work to do in Cordova. If this is unbearable for you, please come help us out. Your comment does nothing but demotivate me

**Comment by jcesarmobile** [comment]
@andreszs I've been reading some of your comments and issues that you have been opening in different projects and it's not the first time you publicly embarrass yourself because of your lack of knowledge.

But don't get me wrong, your lack of knowledge is not the problem here, your problem is the lack of respect to other people work and the way of communicating it.
If you don't fully understand how something work, you can politely ask. If you think that you understand how something work, you still have to be polite and don't disrespect the people who did the work and offered for free. We are humans and we are not perfect, so sometimes we make mistakes, and introduce bugs or don't consider all use cases. When this happen we really appreciate people reporting them.
I feel your pain and I understand that you can get angry because of a bug that affects you, but that doesn't entitle you to be rude on your comments. 

To help you with your lack of knowledge, I'm going to explain to you how we work with jira and github.

- Somebody report a bug on jira.
- Somebody start working on the bug
- When he finds a solution he send a pull request to github.
- The pull request is reviewed and if everything is ok then it's merged
- The status of the jira issue is changed to fixed and a fix version is set.

After a few bugs has been fixed, then we do a release including all of them.

In https://issues.apache.org/jira/browse/CB-12856 you can see that the fix version is set to cordova-ios@4.4.1.
Which version do you have installed? I assume you have 4.4.0 because it's the latest released one, that means you don't have the fix yet.
If you can't wait until this version is released, you can get the fix using nightly versions or installing the platform from the github master branch.

I hope this helped you to understand how things work.

I also hope that you start respecting other people work and be more respectful when you write your next comment or create your next issue.

**Comment by andreszs** [comment]
@jcesarmobile Thanks for the clarification... I'll try to cool down before posting next time. I was just too frustrated after noticing the bug is marked as fixed, but I failed to notice it wasn't fixed for the current release as you mentioned, sorry for that.

**Pull request closed without merging**
